version: '2'
services:
  longhorn-driver:
    privileged: true
    pid: host
    image: rancher/storage-longhorn:v0.7.0
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: 'environment'
    volumes:
    - /run:/run
    - /var/run:/var/run
    - /dev:/host/dev
    - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
    - /var/lib/rancher/longhorn:/var/lib/rancher/longhorn
    environment:
      RANCHER_DEBUG: ${RANCHER_DEBUG}
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'

  longhorn-orc:
    image: imikushin/longhorn-orc:e9b6fa6
    expose:
    - 7000:7000/tcp
    labels:
      io.rancher.sidekicks: longhorn-binary
      io.rancher.scheduler.global: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: 'environment'
    volumes:
    - /var/run:/var/run
    volumes_from:
    - longhorn-binary   # /usr/local/bin
    environment:
      RANCHER_DEBUG: ${RANCHER_DEBUG}
      LONGHORN_IMAGE: rancher/longhorn:5c4b8bb

  longhorn-binary:
    image: rancher/longhorn:5c4b8bb
    command: [sh]
    stdin_open: true
    tty: true

  longhorn-orc-lb:
    image: rancher/lb-service-haproxy:v0.6.2
    ports:
    - 7000:7000/tcp
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent.role: environmentAdmin
